### ISSUE TITLE
Spout Source not shown in OBS plugins when Prprlive Alpha Channel Source Plugin installed

### ISSUE THREAD

**Issue by baoziii** [emilianavt/VSeeFaceManual#1]
This is not an issue, but could you please add this reminder to the manual? 
I tried to use the Spout source OBS plugin to pull the VSeeFace image. I followed the `spout.md`, but the plugin is not shown in the OBS. Then, I checked the OBS log and found that the Prprlive α-Channel plugin (a modified version of the Spout, used for pulling the transparent image from Prprlive) duplicated the name with Spout, and it cannot receive other sources rather than Prprlive. The Spout works after removing the `prpr-library.dll` in the obs-plugin folder. Prprlive does not provide the plugin uninstall function. In addition, you can receive the image from both VSeeFace and Prprlive after using the Spout Caputure.
Could you please add this reminder? It may be helpful for the people who use both the VSeeFace and Prprlive. Thank you!

**Comment by emilianavt** [comment]
Hi! Thank you for letting me know about this issue! I'll add a note to the documentation.

Edit: I added a note.
